### ISSUE TITLE
Does not work with Vue JS application using nuxt

### ISSUE THREAD

**Issue by claudemangen** [TechTeamer/janus-api#15]
Hello,

When using your module in a vue application, generated bundle fails with errors related to websocket.

I am not sure what is happening, but the following dirty fix made it work:

https://github.com/claudemangen/janus-api/commit/48695e97d6080b43ba836cbeebf2df3db40230d6

Regards

**Comment by tgabi333** [comment]
In this case we should handle websocket as an external dependency passed through constructors, contribution warmly welcomed

**Comment by tgabi333** [comment]
Fixed in https://github.com/TechTeamer/janus-api/pull/18, released in 6.1.0
