### ISSUE TITLE
Http instead of ws connection

### ISSUE THREAD

**Issue by trojek** [TechTeamer/janus-api#16]
Is is possibile to use http instead of ws to connect with janus-gateway?

**Comment by tgabi333** [comment]
Sure, but not with this library. Check out the docs: https://janus.conf.meetecho.com/docs/transport_8h.html

**Comment by trojek** [comment]
I find this library very usefull and I wanted to use it but with https, due to  problems with ws reverse proxy on nginx. Is is possible to modify TechTeamer/janus-api to use http instead of ws? Could you give me some hints what should I change?

**Comment by uwejan** [comment]
Another question here, is it possible to not use web-socket neither http but use mqtt ?
