### ISSUE TITLE
Publisher.js TypeError: navigator.mediaDevices is undefined

### ISSUE THREAD

**Issue by uwejan** [TechTeamer/janus-api#24]
Hi, on fresh run of the test dir. i get the following error. please advice.
` TypeError: navigator.mediaDevices is undefined
    [43]</</</< publisher.js:83
publisher.js:110`
Thanks.

**Comment by tgabi333** [comment]
Hi @uwejan !

are you using https? which browser?

**Comment by uwejan** [comment]
@tgabi333 I have disabled https. Latest chrome and firefox.

**Comment by tgabi333** [comment]
both browsers needs https for allowing media devices (camera) access. 

Try to set this crhome: chrome://flags/#allow-insecure-localhost for testing purposes

**Comment by uwejan** [comment]
I already done that.
Also I notice you specify the rtp ports, is not supposed to be coming from the answer.
Also if you do not mind, what server are you using on your turn server?

**Comment by tgabi333** [comment]
with this flag you can use a self-signed cert for https and you can access media devices.

for turn server i can advice coturn.

**Comment by uwejan** [comment]
I should be able to report back after an hour.

**Comment by uwejan** [comment]
@tgabi333 Using mkcert , had a cert for pc1 running the test. and a cert for pc2 running janos.
I have /etc/hosts record pointing janus.dev to pc2 on pc1. all ping-able both sides.
![gnome-shell-screenshot-TDFFQ0](https://user-images.githubusercontent.com/20250935/92636779-95520d00-f2e0-11ea-8c7b-599aff56d47a.png)
Am going to host janus on the internet on a subdomain and see if that works.

**Comment by uwejan** [comment]
Ssl issue. Had to host janus with ssl enabled. Problem went off and all good.
1 question though, am still trying to wrap my head around how webrtc client server communicate, is it manadtory to specify rtp ports for audio and video?
Qnother question, while having same code base, is it possible to pass janus instance to the class handeling viewers, in case of videoRoom test?
3. Passing video and audio true to video room for screensharing does not send ausio, can you please confirm if its working for you, ausio and video with screenshare?
