### ISSUE TITLE
Using mqtt advice.

### ISSUE THREAD

**Issue by uwejan** [TechTeamer/janus-api#25]
My app already has an mqtt connection, I wish to make use of the mqtt trasnporter. If i wish to modify the package to work with mqtt. I firat hqve to address the req/res nqture, and differences of pub sub on other hand. What other concepts would you add to my task list? Do you think its feasable ?
Many thanks.

**Comment by tgabi333** [comment]
I think its feasible. You only need to extend `Janus` class and implement the logic inside for serving plugins.

**Comment by uwejan** [comment]
@tgabi333, Started working on this. Since mqttt nature based on pub/sub i found that many Methods needs has to be overridden for convenience am going to be modifying the original code instead.
Now I can create new mqtt connection but then the browser will end up making 2 mqtt connections since the app already have 1 connection.
#1 So, i wonder What technique would you suggest for passing an mqtt client connection to the lib?

**Comment by uwejan** [comment]
@tgabi333 Thanks to your implementation i managed to get a quick mqtt implementation.
https://github.com/uwejan/janus-api-mqtt
Thanks Again.
