### ISSUE TITLE
awesome plugin

### ISSUE THREAD

**Issue by jason-shen** [TechTeamer/janus-api#9]
Looks very clean compare with the official one, it would be good if you could do some docs for it, i have a looked around and just don't know where to start with this

**Comment by tgabi333** [comment]
Hi Jason!

For examples, please take a look at test folder

**Comment by jason-shen** [comment]
Cheers for the reply

I did that, the test seems for server side codes, I have try it with react, it doesn’t go well with the test code



Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
Those test are running in browser, see test/buildtest.js

**Comment by jason-shen** [comment]
When I build for react this comes up

./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in '/Volumes/DEVELOPMENT/react/web/webrtc/node_modules/ws/lib'

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/Volumes/DEVELOPMENT/react/web/webrtc/node_modules/ws/lib'



Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
Which nodr version are you using?

**Comment by jason-shen** [comment]
8.1.1

Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
we use ws library on nodejs side to have websocket, in the browser we did not need it. You can check: https://github.com/TechTeamer/janus-api/blob/master/src/WebSocket.js

Try not to include ws in the build

**Comment by jason-shen** [comment]
Got it as ws is included in the npm package how would I exclude it with the react build

Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
May be this can help: https://github.com/socketio/socket.io-client/issues/933

**Comment by jason-shen** [comment]
Yeah I have read that, but I am not using webpack so not sure where to go from here

Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
How do you build?

**Comment by jason-shen** [comment]
Create-react-app

The cli of react does the building

"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build --exclude=node_modules/ws",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },


Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
I've sucsessfully built sample react app by putting `externals: ['ws']` line in the webpack configuration node_modules/react-scripts/config/webpack.config.dev.js

**Comment by tgabi333** [comment]
however i couldn't find a way how to override that webpack config :S  
but this is a quick and dirty solution:
```
  "scripts": {
    "start": "rm -rf ./node_modules/ws && react-scripts start",
    "build": "rm -rf ./node_modules/ws && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
```

**Comment by jason-shen** [comment]
cool will give that a go thanks

发自我的iPhone


------------------ Original ------------------

**Comment by jason-shen** [comment]
Try it but your lib don’t like it here is the error

./node_modules/@techteamer/janus-api/src/WebSocket.js
Module not found: Can't resolve 'ws' in '/Volumes/DEVELOPMENT/react/web/webrtc/node_modules/@techteamer/janus-api/src'

Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by jason-shen** [comment]
This actually worked thanks

Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by jason-shen** [comment]
Hi Gabor

I am playing around with the awesome lib, just wondering, any chance implementing the rest of the plugins, like video/voice calls between user and sip
That would be great if you can

thanks

Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by jason-shen** [comment]
I have manage to get it running, with couple of problems,


  1.  Only I can publish or listen to the room, others can’t seem to join
  2.  Please see the image I have a error log coming back from the server, not sure what that means

Any help would be great, thanks advance



Kind Regards,
[cid:image001.png@01D3E3F3.37DF5E60]

**Comment by tgabi333** [comment]
For one client you should create a publisher and several listeners

**Comment by jason-shen** [comment]
![screen shot 2018-05-22 at 3 40 13 am](https://user-images.githubusercontent.com/1794291/40420855-534429c6-5ebc-11e8-9c31-5b9c4406e9fa.png)

also have you come across this error?

**Comment by tgabi333** [comment]
yep, its not a real error. slow_link means that janus discovered that one of the connection is weak.

**Comment by jason-shen** [comment]
ok so its good then, if reduce the video res should be fix this warning right

**Comment by jason-shen** [comment]
one more question while i have you online
1. if want to make a video chat(more than one publisher) just do more than one publisher, is that correct.

2. is it possible to do 1 one 1 call with the plugin
